export enum Tag {
  A = 'a',
  Button = 'button',
  Div = 'div',
  Paragraph = 'p',
  H1 = 'h1',
  H2 = 'h2',
  H3 = 'h3',
  H4 = 'h4',
  H5 = 'h5',
  H6 = 'h6',
  Footer = 'footer',
  Form = 'Form',
  Header = 'header',
  Img = 'img',
  Span = 'span',
  Source = 'source',
  Svg = 'svg',
  Input = 'input',
  Textarea = 'textarea',
  Label = 'label',
  Ul = 'ul',
  Ol = 'ol',
  Li = 'li',
  Video = 'video',
  Vue = 'vue',
  Canvas = 'canvas',
}

export type TagType = `${Tag}`
