export enum Keys {
  Escape = 'Escape',
  ArrowUp = 'ArrowUp',
  ArrowDown = 'ArrowDown',
  ArrowLeft = 'ArrowLeft',
  ArrowRight = 'ArrowRight',
  Enter = 'Enter',
  Delete = 'Backspace',
  Tab = 'Tab',
  LowerC = 'c',
  UpperC = 'C',
  LowerD = 'd',
  UpperD = 'D',
  LowerV = 'v',
  UpperV = 'V',
  Z = 'z',
}
