[package]
name = "lib-shared-site-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib_shared_site_api"
path = "src/lib.rs"

[dependencies]
lib-shared-types = { path = "../lib-shared-types" }
axum = { version = "0.6.18", features = ["headers"] }
axum-macros = "0.3.7"
base64 = "0.21.0"
chrono = "0.4.24"
lazy_static = "1.4.0"
jsonwebtoken = "8.3.0"
reqwest = { version = "0.11.18", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
sqlx = { version = "0.6.3", features = ["runtime-tokio-rustls", "chrono"] }
strum = { version = "0.24.1", features = ["derive"] }
thiserror = "1.0.40"
tokio = "1.28.1"
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
tracing-bunyan-formatter = { default-features = false, version = "0.3" }
uuid = { version = "1.3.3", features = ["serde", "v4"] }
validator = "0.16.0"
regex = "1.8.3"
rusty-s3 = "0.4.1"
tower = "0.4.13"
tracing-core = "0.1.31"
nu-ansi-term = "0.47.0"
moka = { version = "0.12.0-beta.1", features = ["future"] }
file-rotate = "0.7.3"
aes = "0.8.3"
cbc = { version = "0.1.2", features = ["std"] }
urlencoding = "2.1.3"
