### Reset Site API
POST http://localhost:3001/actions/reset/site
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMTFiMTdmMi00ODhmLTQ1YzEtOTBhNS1mZDRkNDE5ZWE1MDUiLCJ1c2VyX3R5cGUiOiJBZG1pbiIsImlhdCI6MTY4NDcyODExNCwiZXhwIjoxNjg3MzIwMTE0fQ.sFt7tumJtcbRYaciQIquty8a0jd1l43Xbv_Gd8oU3sN3rql4i0cxcQuRIbbpwL9ImajCOxdkeSqdAhyFSYJ5-TBKj4ACOLg4gFEc-hVGHvT5BCZ1YPUIb3dny8pAe85oMWj-wWkEMaRZIfwqJjzQ5HnIFa-W_LGOR6h4ioxNujg7p8GoFsJI-3rcwGeNbpQ2sYzESZQ0uWxJpQn7AnJoqU1s5RROMoHKEbT-hgQjqMKN1txMInNH91SmYAMjG-gf9ZNXJfbrk-_O-wzsolVJcwDLp3jRLfIG5pURzBY3VrwR7TE79ADb7-FeWYBWLz5LU-2_4a_UmKRaaHQC_iyn5kwgrBwurTfV2MBZYOjtdYLydNrOKhtF4_5Goy5c_LloDtltCsEX1uf4iX61kJyvgTWKmQrRsWSVTloMOQFIBlzvT8qUFknPW_iNO5hma0wvDQQOwVvx79BwFH7VGZrsk9DWlQOnHmn0kxYMK-ZrEIGE2zMvyF_v4rRL5RYZKbf7347SZeS5sZSkh_k-qq_VpLhQgdu7VuvWdff_oOEGT1GnDiIW0PRpaC5cm4pMJda2Wfkdjk_iXnfvjCGiR6hFzb2tENTUS2QMdK_BXjHKs2Zy0wiz9XJ1dHWufTyujhw1CmhDGjdBVx4n71AxkXFeCFE2l8l2UVeStDFkZsxtr1c

{
  "address": "http://site-api1:3100",
  "seed": true
}

### Create Site
POST http://localhost:3100/sites
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGQ0ODQzZS00YjgzLTQzNDAtOTEwNC01YjIyNWFlNTUxZDUiLCJ1c2VyX3R5cGUiOiJBZG1pbiIsImlhdCI6MTY4ODIyMjg3OSwiZXhwIjoxNjkwODE0ODc5fQ.MtVn_YqsXvuVjJSdRfJa8keQ1H8s9hcEZpWQGoIcttZFU1m9Q5OMrOftBV8CDtX37rxiwMD_gan3vPm6jFoCc6_jrJkyTX9R-JVDHhgMvTa5YAXhg7O2rkxCKBrR9bLqPk2qwVJrB8QJ1XMRxuuHfwXkl_gNLe5QuOaKX7Fg6w9_8uTlj0YcbgnZKr6zTDlJ01b0z4EReYbhSqxkveVwUcM7xVwfz5LTTWqNTzd9wa7f6ye3QqZVq7y-tlsmBumFA2FedeKKqBDnIRi8QKNFIo_IjB19wyFy-Rpf6JIqNG6G5459QKI0opg9dV2pWzVgUds3-j-aCbfrylmJXCvT65gO_o0TdZgnS0JJWEA8EfcCm3iXz0LYH_HqCrkvsQFP4UIDP09kX3REuylpXXpm2KtAV1-J-tBmL1-fB_2u6DKVpq3LglJwDRyVSq5O5KIe_wsCOI6rg0hmiMO42mZxCRNhfqU4BoMrMtxDzHMfYIHFp7-vXZL8llWZcOd3HcuvfTnL2Wu4iTdgYnPbaQJPuP71mUBsdet6i-jfnOP9P42aYOr0sJejZoUXIBb75jd03xwcWfYl7KSyCVaOsFV9O2L6oLc6iFLVBZ2jh3Mvo4mkOsLYkL4kdsQ7QWaYDhzFQukJDMdpvgZBJG1JR8pctkjlxJy4W92pMQzsuVs3BeA

{
  "id": "942ee184-9f60-45f6-85b6-360226cce209",
  "owner_id": "96d2965c-59d1-42fd-938e-34f4e230dc43",
  "name": "Test Site",
  "published": false,
  "data": "{\\\"some\\\":\\\"stringified_json\\\"}"
}

### Get Site by ID
GET http://localhost:3100/sites/870aafc9-36e9-476a-b38c-c1aaaad9d9fe

### List Sites
GET http://localhost:3100/sites
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGQ0ODQzZS00YjgzLTQzNDAtOTEwNC01YjIyNWFlNTUxZDUiLCJ1c2VyX3R5cGUiOiJBZG1pbiIsImlhdCI6MTY4ODIyMjg3OSwiZXhwIjoxNjkwODE0ODc5fQ.MtVn_YqsXvuVjJSdRfJa8keQ1H8s9hcEZpWQGoIcttZFU1m9Q5OMrOftBV8CDtX37rxiwMD_gan3vPm6jFoCc6_jrJkyTX9R-JVDHhgMvTa5YAXhg7O2rkxCKBrR9bLqPk2qwVJrB8QJ1XMRxuuHfwXkl_gNLe5QuOaKX7Fg6w9_8uTlj0YcbgnZKr6zTDlJ01b0z4EReYbhSqxkveVwUcM7xVwfz5LTTWqNTzd9wa7f6ye3QqZVq7y-tlsmBumFA2FedeKKqBDnIRi8QKNFIo_IjB19wyFy-Rpf6JIqNG6G5459QKI0opg9dV2pWzVgUds3-j-aCbfrylmJXCvT65gO_o0TdZgnS0JJWEA8EfcCm3iXz0LYH_HqCrkvsQFP4UIDP09kX3REuylpXXpm2KtAV1-J-tBmL1-fB_2u6DKVpq3LglJwDRyVSq5O5KIe_wsCOI6rg0hmiMO42mZxCRNhfqU4BoMrMtxDzHMfYIHFp7-vXZL8llWZcOd3HcuvfTnL2Wu4iTdgYnPbaQJPuP71mUBsdet6i-jfnOP9P42aYOr0sJejZoUXIBb75jd03xwcWfYl7KSyCVaOsFV9O2L6oLc6iFLVBZ2jh3Mvo4mkOsLYkL4kdsQ7QWaYDhzFQukJDMdpvgZBJG1JR8pctkjlxJy4W92pMQzsuVs3BeA

### Update Site by ID
PATCH http://localhost:3100/sites/6d2c8359-6094-402c-bcbb-37202fd7c336
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGQ0ODQzZS00YjgzLTQzNDAtOTEwNC01YjIyNWFlNTUxZDUiLCJ1c2VyX3R5cGUiOiJBZG1pbiIsImlhdCI6MTY4ODIyMjg3OSwiZXhwIjoxNjkwODE0ODc5fQ.MtVn_YqsXvuVjJSdRfJa8keQ1H8s9hcEZpWQGoIcttZFU1m9Q5OMrOftBV8CDtX37rxiwMD_gan3vPm6jFoCc6_jrJkyTX9R-JVDHhgMvTa5YAXhg7O2rkxCKBrR9bLqPk2qwVJrB8QJ1XMRxuuHfwXkl_gNLe5QuOaKX7Fg6w9_8uTlj0YcbgnZKr6zTDlJ01b0z4EReYbhSqxkveVwUcM7xVwfz5LTTWqNTzd9wa7f6ye3QqZVq7y-tlsmBumFA2FedeKKqBDnIRi8QKNFIo_IjB19wyFy-Rpf6JIqNG6G5459QKI0opg9dV2pWzVgUds3-j-aCbfrylmJXCvT65gO_o0TdZgnS0JJWEA8EfcCm3iXz0LYH_HqCrkvsQFP4UIDP09kX3REuylpXXpm2KtAV1-J-tBmL1-fB_2u6DKVpq3LglJwDRyVSq5O5KIe_wsCOI6rg0hmiMO42mZxCRNhfqU4BoMrMtxDzHMfYIHFp7-vXZL8llWZcOd3HcuvfTnL2Wu4iTdgYnPbaQJPuP71mUBsdet6i-jfnOP9P42aYOr0sJejZoUXIBb75jd03xwcWfYl7KSyCVaOsFV9O2L6oLc6iFLVBZ2jh3Mvo4mkOsLYkL4kdsQ7QWaYDhzFQukJDMdpvgZBJG1JR8pctkjlxJy4W92pMQzsuVs3BeA

{
  "name":"New Test Site",
  "data":"{\"some\":\"yayaya_test\"}"
}

### Delete Site by ID
DELETE http://localhost:3100/sites/6d2c8359-6094-402c-bcbb-37202fd7c336
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGQ0ODQzZS00YjgzLTQzNDAtOTEwNC01YjIyNWFlNTUxZDUiLCJ1c2VyX3R5cGUiOiJBZG1pbiIsImlhdCI6MTY4ODIyMjg3OSwiZXhwIjoxNjkwODE0ODc5fQ.MtVn_YqsXvuVjJSdRfJa8keQ1H8s9hcEZpWQGoIcttZFU1m9Q5OMrOftBV8CDtX37rxiwMD_gan3vPm6jFoCc6_jrJkyTX9R-JVDHhgMvTa5YAXhg7O2rkxCKBrR9bLqPk2qwVJrB8QJ1XMRxuuHfwXkl_gNLe5QuOaKX7Fg6w9_8uTlj0YcbgnZKr6zTDlJ01b0z4EReYbhSqxkveVwUcM7xVwfz5LTTWqNTzd9wa7f6ye3QqZVq7y-tlsmBumFA2FedeKKqBDnIRi8QKNFIo_IjB19wyFy-Rpf6JIqNG6G5459QKI0opg9dV2pWzVgUds3-j-aCbfrylmJXCvT65gO_o0TdZgnS0JJWEA8EfcCm3iXz0LYH_HqCrkvsQFP4UIDP09kX3REuylpXXpm2KtAV1-J-tBmL1-fB_2u6DKVpq3LglJwDRyVSq5O5KIe_wsCOI6rg0hmiMO42mZxCRNhfqU4BoMrMtxDzHMfYIHFp7-vXZL8llWZcOd3HcuvfTnL2Wu4iTdgYnPbaQJPuP71mUBsdet6i-jfnOP9P42aYOr0sJejZoUXIBb75jd03xwcWfYl7KSyCVaOsFV9O2L6oLc6iFLVBZ2jh3Mvo4mkOsLYkL4kdsQ7QWaYDhzFQukJDMdpvgZBJG1JR8pctkjlxJy4W92pMQzsuVs3BeA

### Publish Site by ID
POST http://localhost:3100/sites/6d2c8359-6094-402c-bcbb-37202fd7c336/actions/publish
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGQ0ODQzZS00YjgzLTQzNDAtOTEwNC01YjIyNWFlNTUxZDUiLCJ1c2VyX3R5cGUiOiJBZG1pbiIsImlhdCI6MTY4ODIyMjg3OSwiZXhwIjoxNjkwODE0ODc5fQ.MtVn_YqsXvuVjJSdRfJa8keQ1H8s9hcEZpWQGoIcttZFU1m9Q5OMrOftBV8CDtX37rxiwMD_gan3vPm6jFoCc6_jrJkyTX9R-JVDHhgMvTa5YAXhg7O2rkxCKBrR9bLqPk2qwVJrB8QJ1XMRxuuHfwXkl_gNLe5QuOaKX7Fg6w9_8uTlj0YcbgnZKr6zTDlJ01b0z4EReYbhSqxkveVwUcM7xVwfz5LTTWqNTzd9wa7f6ye3QqZVq7y-tlsmBumFA2FedeKKqBDnIRi8QKNFIo_IjB19wyFy-Rpf6JIqNG6G5459QKI0opg9dV2pWzVgUds3-j-aCbfrylmJXCvT65gO_o0TdZgnS0JJWEA8EfcCm3iXz0LYH_HqCrkvsQFP4UIDP09kX3REuylpXXpm2KtAV1-J-tBmL1-fB_2u6DKVpq3LglJwDRyVSq5O5KIe_wsCOI6rg0hmiMO42mZxCRNhfqU4BoMrMtxDzHMfYIHFp7-vXZL8llWZcOd3HcuvfTnL2Wu4iTdgYnPbaQJPuP71mUBsdet6i-jfnOP9P42aYOr0sJejZoUXIBb75jd03xwcWfYl7KSyCVaOsFV9O2L6oLc6iFLVBZ2jh3Mvo4mkOsLYkL4kdsQ7QWaYDhzFQukJDMdpvgZBJG1JR8pctkjlxJy4W92pMQzsuVs3BeA

{
  "version_id": 1
}

### Get Site by Version ID
GET http://localhost:3100/sites/870aafc9-36e9-476a-b38c-c1aaaad9d9fe/versions/latest
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGQ0ODQzZS00YjgzLTQzNDAtOTEwNC01YjIyNWFlNTUxZDUiLCJ1c2VyX3R5cGUiOiJBZG1pbiIsImlhdCI6MTY4ODIyMjg3OSwiZXhwIjoxNjkwODE0ODc5fQ.MtVn_YqsXvuVjJSdRfJa8keQ1H8s9hcEZpWQGoIcttZFU1m9Q5OMrOftBV8CDtX37rxiwMD_gan3vPm6jFoCc6_jrJkyTX9R-JVDHhgMvTa5YAXhg7O2rkxCKBrR9bLqPk2qwVJrB8QJ1XMRxuuHfwXkl_gNLe5QuOaKX7Fg6w9_8uTlj0YcbgnZKr6zTDlJ01b0z4EReYbhSqxkveVwUcM7xVwfz5LTTWqNTzd9wa7f6ye3QqZVq7y-tlsmBumFA2FedeKKqBDnIRi8QKNFIo_IjB19wyFy-Rpf6JIqNG6G5459QKI0opg9dV2pWzVgUds3-j-aCbfrylmJXCvT65gO_o0TdZgnS0JJWEA8EfcCm3iXz0LYH_HqCrkvsQFP4UIDP09kX3REuylpXXpm2KtAV1-J-tBmL1-fB_2u6DKVpq3LglJwDRyVSq5O5KIe_wsCOI6rg0hmiMO42mZxCRNhfqU4BoMrMtxDzHMfYIHFp7-vXZL8llWZcOd3HcuvfTnL2Wu4iTdgYnPbaQJPuP71mUBsdet6i-jfnOP9P42aYOr0sJejZoUXIBb75jd03xwcWfYl7KSyCVaOsFV9O2L6oLc6iFLVBZ2jh3Mvo4mkOsLYkL4kdsQ7QWaYDhzFQukJDMdpvgZBJG1JR8pctkjlxJy4W92pMQzsuVs3BeA

### List Site Versions
GET http://localhost:3100/sites/6d2c8359-6094-402c-bcbb-37202fd7c336/versions?from=1&to=2
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGQ0ODQzZS00YjgzLTQzNDAtOTEwNC01YjIyNWFlNTUxZDUiLCJ1c2VyX3R5cGUiOiJBZG1pbiIsImlhdCI6MTY4ODIyMjg3OSwiZXhwIjoxNjkwODE0ODc5fQ.MtVn_YqsXvuVjJSdRfJa8keQ1H8s9hcEZpWQGoIcttZFU1m9Q5OMrOftBV8CDtX37rxiwMD_gan3vPm6jFoCc6_jrJkyTX9R-JVDHhgMvTa5YAXhg7O2rkxCKBrR9bLqPk2qwVJrB8QJ1XMRxuuHfwXkl_gNLe5QuOaKX7Fg6w9_8uTlj0YcbgnZKr6zTDlJ01b0z4EReYbhSqxkveVwUcM7xVwfz5LTTWqNTzd9wa7f6ye3QqZVq7y-tlsmBumFA2FedeKKqBDnIRi8QKNFIo_IjB19wyFy-Rpf6JIqNG6G5459QKI0opg9dV2pWzVgUds3-j-aCbfrylmJXCvT65gO_o0TdZgnS0JJWEA8EfcCm3iXz0LYH_HqCrkvsQFP4UIDP09kX3REuylpXXpm2KtAV1-J-tBmL1-fB_2u6DKVpq3LglJwDRyVSq5O5KIe_wsCOI6rg0hmiMO42mZxCRNhfqU4BoMrMtxDzHMfYIHFp7-vXZL8llWZcOd3HcuvfTnL2Wu4iTdgYnPbaQJPuP71mUBsdet6i-jfnOP9P42aYOr0sJejZoUXIBb75jd03xwcWfYl7KSyCVaOsFV9O2L6oLc6iFLVBZ2jh3Mvo4mkOsLYkL4kdsQ7QWaYDhzFQukJDMdpvgZBJG1JR8pctkjlxJy4W92pMQzsuVs3BeA
